### ISSUE TITLE
tvdb.com series info not populating in EPG - SchedulesDirect Plugin 1.11.0.1 still shows as 1.3.0.1 - 

### ISSUE THREAD

**Issue by jjemil749** [geoffstewart/mp-schedulesdirect#12]
What steps will reproduce the problem?
1. in TV-Server Configuration -> SchedulesDirect EPG Plugin -> tvdb.com tab
  - put checkmark on "Fetch season and episode information from tvdb.com"
  - add SchedulesDirect series name | tvdb.com Series ID number (checkmark on Series ID)
2. Mark SD to update on next restart
3. Reboot computer
4. Open MediaPortal and set MediaPortal to record upcoming TV series
5. Reboot MediaPortal and open EPG

What is the expected output? What do you see instead?
series info is downloaded to C:\ProgramData\Team MediaPortal\MediaPortal TV Server\tvdblib_cache\seriesIDNumber, but series info doesn't appear in EPG

What version of the product are you using? On what operating system?
MediaPortal 1.11.0, TV-Server 1.11.0 - Windows 10 Technical Preview 64-bit build 10041

Please provide any additional information below.
files attached
![schedulesdirect_version](https://cloud.githubusercontent.com/assets/5369361/6999724/3c6376b0-dbe0-11e4-8e2d-23a31d51f0c8.PNG)

SchedulesDirect Debug files
https://drive.google.com/file/d/0B7QT33zsOZ7dSHVoUGtpcnY3ZVE/view?usp=sharing

**Comment by geoffstewart** [comment]
I fixed the version that is being displayed.

I need more information about the season/episode information not being populated.

**Comment by jjemil749** [comment]
It's fine. Season/episode information is being populated. 

I simply did not know I have to record a TV show as TV series for the seasion/episode info to show.
